### ISSUE TITLE
It shows that my mods have available updates but they are actually up to date

### ISSUE THREAD

**Issue by EGOIST1372** [JamCoreModding/Notify#20]
It shows that my mods have available updates but they are actually up to date and also it crashes when i click on notify mod on mod menu
![2022-02-13_04 39 34](https://user-images.githubusercontent.com/86555131/153734143-36036f12-8ce2-4720-b35c-4f7bf58d30ba.png)

**Comment by Jamalam360** [comment]
I don't think fast furnace is using valid semantic versioning, which is what's messing Notify up here. Once I get around to implementing the Curseforge API it should work better (I've got my key now).

Can you send the logs for the crash when you click on notify in mod menu?

**Comment by EGOIST1372** [comment]
it's not just those that don't use valid semantic versioning, all of the mods that it shows has update is already up to date(example screenshot)
![image](https://user-images.githubusercontent.com/86555131/153753187-5df7d89d-40ce-4bcd-83c6-6fe225fb5be4.png)
and this is the crash log:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/13/22, 4:03 PM
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "io.github.jamalam360.notify.resolver.NotifyVersionChecker$VersionComparisonResult.name()" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.handler$bld000$notify$appendNotifyStatus(DescriptionListWidget.java:577)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.render(DescriptionListWidget.java:104)
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:278)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:875)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.handler$bld000$notify$appendNotifyStatus(DescriptionListWidget.java:577)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.method_25394(DescriptionListWidget.java:104)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:278)

-- Screen render details --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
	Mouse location: Scaled: (74, 208). Absolute: (598.000000, 1665.000000)
	Screen size: Scaled: (480, 270). Absolute: (3840, 2160). Scale factor of 8.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Black Icons, VanillaTweaks_1.18.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 394621104 bytes (376 MiB) / 1006632960 bytes (960 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1617
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 53897.08
	Virtual memory used (MB): 36813.29
	Swap memory total (MB): 21193.22
	Swap memory used (MB): 1236.54
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalbars: Additional Bars 2.2.1
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		architectury: Architectury 3.6.17
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.3
		bedspreads: Bedspreads 1.5.0-1.18
		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		bettersafebed: BetterSafeBed 1.18-fabric-a
		blue_endless_jankson: jankson 1.2.1
		camerautils: Camera Utils 1.18.1-1.0.0
		chalk: Chalk 1.2.1
		chat-up: Chat Up! 2.0
		chat_heads: Chat Heads 0.6.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.0+5
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_yaml: yaml 3.6.5
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_github_reviversmc_modget-lib: modget-lib 3.0.0
		com_github_reviversmc_modget-manifest-api_compat: compat 0.2.1
		com_github_reviversmc_modget-manifest-api_spec3: spec3 0.2.1
		com_github_reviversmc_modget-manifest-api_spec4: spec4 0.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		config2brigadier: Config to Brigadier 1.0.2
		controlling: Controlling For Fabric 9.0+14
		crowdin-translate: CrowdinTranslate 1.4+1.18
		deathlog: DeathLog 0.2.6+1.18
		dynamicfps: Dynamic FPS 2.1.0
		eatinganimationid: Eating Animation 1.2
		entityculling: EntityCulling-Fabric 1.3.3
		enum-extender-3000: Enum Extender 3000 1.1.0
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fabrictailor: Fabric Tailor 1.8.0
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		farsight: Farsight Mod 1.18-1.5
		fastbench: FastBench 1.18.1-3
		fastfurnace: FastFurnace 1.18-4
		ferritecore: FerriteCore 4.0.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		glassdoor: Glass Doors 2.1.0-beta.1+1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		indium: Indium 1.0.2-alpha2+mc1.18.1
		infinitemusic: Infinite Music 1.5.1
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.0-pre
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.7
		maptooltip: Map Tooltip 1.3.1
		microdurability: microDurability 0.3.2+1.18.1
		minecraft: Minecraft 1.18.1
		minecraftcapes: MinecraftCapes Mod 12.0.2
		mm: Manningham Mills 2.3
		modget: Modget 0.4.3+1.17
		modget-core: Modget Core 0.4.3
		modmenu: Mod Menu 3.0.1
		multibeds: MultiBeds 1.2.0
		myron: Myron 1.6.1-1.17.1
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		notes: Notes 1.0.10
		notify: Notify 1.3.0
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_yaml_snakeyaml: snakeyaml 1.29
		paintingcycle: Painting Cycle 1.0.0
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.4.0
		roughlyenoughitems: Roughly Enough Items 7.2.425
		screenshotclipboard: Screenshot to Clipboard 1.0.7
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.18
		sheepconsistency: Sheep Consistency 1.0.3
		shetiphiancore: ShetiPhianCore 1.2.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		sneakyscreens: Sneaky Screens 1.0.1
		sodium: Sodium 0.4.0-alpha6+build.14
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.4
		tooltipfix: ToolTip Fix 1.0.4-1.18
		umollu_ash: ASH - Another Simple HUD 1.1.16
		voicechat: Simple Voice Chat 1.18.1-2.2.16
		waveycapes: WaveyCapes 1.0.4
		wi_zoom: WI Zoom 1.3-MC1.18.1
		windchimes: Windchimes 1.2.0
		wmch: Where's My Chat History 1.4.3
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 980M/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, Black Icons, file/VanillaTweaks_1.18.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Mod Menu (modmenu)


	it seems your mod make mod menu to crash

**Comment by Jamalam360** [comment]
I'll be working on this for the release of V2.0.0 soon

**Comment by EGOIST1372** [comment]
@Jamalam360 any news?

**Comment by Jamalam360** [comment]
No sorry, I've been super busy and still need to work out where I'm taking this mod

**Comment by EGOIST1372** [comment]
It's ok no worries, I just wanted to know what happened. take care <3
