### ISSUE TITLE
Crash: Incompatible with Fabulous Clouds in Mod Menu

### ISSUE THREAD

**Issue by Lystraeus** [JamCoreModding/Notify#23]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 27/04/2022, 22:43
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "io.github.jamalam360.notify.resolver.NotifyVersionChecker$VersionComparisonResult.name()" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.handler$bln000$notify$appendNotifyStatus(DescriptionListWidget.java:577)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.render(DescriptionListWidget.java:100)
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:278)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.handler$bln000$notify$appendNotifyStatus(DescriptionListWidget.java:577)
	at com.terraformersmc.modmenu.gui.widget.DescriptionListWidget.method_25394(DescriptionListWidget.java:100)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:278)

-- Screen render details --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
	Mouse location: Scaled: (272, 172). Absolute: (545.000000, 345.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, OG_Credits.zip, Silent Elder Guardian Curse.zip, pmc-mob-pack-creeper_jappa-styled-creeper.zip, xali's+Enchanted+Books+v0.9.zip, VanillaTweaks_r830908.zip, visualoverhaul/rounddiscs, betterbeds/fancybeds, betterbeds/connectedbeds
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2383)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 725658624 bytes (692 MiB) / 1073741824 bytes (1024 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600X Six-Core Processor           
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6079
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18766.86
	Virtual memory used (MB): 8992.37
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.88
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		architectury: Architectury 4.1.44
		armorhotswap: ArmorHotswap 1.7
		armorsoundtweak: Armor Sound Tweak 5.0.0
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.2.4
		bettershields: Better Shields 0.0.1-1.18.2
		betterthirdperson: Better Third Person 1.7.3
		blue_endless_jankson: jankson 1.2.1
		brb: Better Recipe Book 1.5.6
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		continuebutton: Continue Button 1.0.4
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		deathlog: DeathLog 0.2.7+1.18
		dynamicfps: Dynamic FPS 2.1.0
		eggtab: Egg Tab 2.2.0+1.18-fabric
		enchantment_lore: Enchantment Lore 1.2.6-1
		entityculling: EntityCulling-Fabric 1.5.1
		enum-extender-3000: Enum Extender 3000 1.1.0
		environmentalcreepers: Environmental Creepers 1.6.0
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		fabulousclouds: Fabulous Clouds 0.3.0
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		ferritecore: FerriteCore 4.2.1
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		impactfulweather: Biome Particle Weather 2.4.6
		inventoryhotswap: Inventory Hotswap 1.3.0
		inventorysorter: Inventory Sorter 1.8.6-1.18
		itemscroller: Item Scroller 0.16.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.1.9
		kyrptconfig: Kyrpt Config 1.4.2-1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazy-language-loader: lazy-language-loader 0.3.0
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.9
		malilib: MaLiLib 0.12.1
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		minihud: MiniHUD 0.22.0
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.2.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		notify: Notify 1.3.0
		onsoulfire: On Soul Fire 1.18-1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		phosphor: Phosphor 0.8.1
		pride: Pride Lib 1.1.0+1.17
		recipecache: recipecache 0.2.1-1.17.1
		replanter: Replanter 1.3
		resounding: Resounding 1.0.0-bc.9
		searchablecontainers: Searchable Containers 1.3
		secondchance: Second Chance 1.3.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.7+1.18.2
		smoke_suppression: Smoke Suppression 1.0.9-1
		sodium: Sodium 0.4.1+build.15
		spruceui: SpruceUI 3.3.0+1.17
		visualoverhaul: VisualOverhaul 4.1.0
		xaeroworldmap: Xaero's World Map 1.20.6
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.79, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/OG_Credits.zip (incompatible), file/Silent Elder Guardian Curse.zip (incompatible), file/pmc-mob-pack-creeper_jappa-styled-creeper.zip (incompatible), file/xali's+Enchanted+Books+v0.9.zip (incompatible), file/VanillaTweaks_r830908.zip, visualoverhaul/rounddiscs, betterbeds/fancybeds (incompatible), betterbeds/connectedbeds (incompatible)
	Current Language: English (United Kingdom)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Mod Menu (modmenu)

**Comment by Jamalam360** [comment]
Thanks, will be done in 2.0.0
